### ISSUE TITLE
Be able to cover encryption in Tests

### ISSUE THREAD

**Issue by Dreijnde** [flux-capacitor-io/flux-capacitor-client#35]
I would like to start a test like this:

<img width="804" alt="image" src="https://github.com/user-attachments/assets/6b2488b2-2f8b-4777-90de-12755e0f522c">

One issue is that DecryptingPropertySource tries to decrypt all properties, including this key itself

Second issue is when starting multiple tests that DefaultPropertySource is a static that set once the first test class kicks off. 
Getting the DefaultPropertySource out of the FluxCapacitor propertysource is annoying to do

<img width="804" alt="image" src="https://github.com/user-attachments/assets/347d3138-699a-4a59-9ee5-a9237c64f21b">

**Comment by renedewaele** [comment]
Fixed in commit #b4fff7ebb37ddc153b34d2d50aba873dd3c4338c
