### ISSUE TITLE
@HandleResult doesn't work in tests 

### ISSUE THREAD

**Issue by Dreijnde** [flux-capacitor-io/flux-capacitor-client#36]
I have an @HandleResult listening to an object returned in the end of another @HandleCommand flow in another class.
No local handlers, and async testfixture, the @HandleResult is not reached when debugging.

The command was thrown as sendAndForgetCommand, I would still expect to be able to listen to the Results though.

Result handler with unreached debug step:
<img width="918" alt="image" src="https://github.com/user-attachments/assets/6bea2d50-23ec-47d4-bc89-56293368deb8">

Start of command handler
<img width="890" alt="image" src="https://github.com/user-attachments/assets/8545fb79-8a66-4938-91b2-aa0ec901ee7b">

End of command handler, with reached debug step:
<img width="890" alt="image" src="https://github.com/user-attachments/assets/d9f4f343-71a6-4148-a8e6-c87488a73ba2">

**Comment by renedewaele** [comment]
When a command is sent via sendAndForget the result is not posted. Use sendCommand instead (ignoring the returned CompletableFuture) if you want to handle the result via @HandleResult.
